variables:
  USERNAME: senali20119025
  PASSWORD: maneesha123

stages:
  - build
  - deploy
  - blue/green deploy
  - switch

docker-build:
    image: docker:latest
    stage: build
    when: manual
    services:
    - docker:dind  
    before_script:
    - docker login -u $USERNAME -p $PASSWORD     
    script:
    - docker build -t "senali20119025/coinbased-exchange-repo:v2" .
    - docker push "senali20119025/coinbased-exchange-repo:v2"

deploy:
    image: google/cloud-sdk
    stage: deploy
    when: manual
    environment:
        name: development
        url: http://development-$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN
        kubernetes:
          namespace: development

    script:
        - kubectl apply -f coinbase-deployment.yaml
        - kubectl apply -f coinbase-service.yaml
        - kubectl get pods
        - kubectl get svc
        - echo done
    only: 
        - master

deploy-blue:
    image: google/cloud-sdk
    stage: blue/green deploy    
    when: manual
    environment:
        name: production
        kubernetes:
          namespace: production
    script:
        - kubectl apply -f app-deployment-blue.yaml
        - kubectl apply -f app-service-blue.yaml
        - kubectl get pods
        - kubectl get svc
        - echo done
    only: 
        - master

deploy-green:
    image: google/cloud-sdk
    stage: blue/green deploy
    when: manual
    environment:
        name: production
        kubernetes:
          namespace: production
    script:
        - echo $KUBE_NAMESPACE
        - echo http://development-$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN
        - kubectl apply -f app-deployment-green.yaml
        - kubectl apply -f app-service-green.yaml
        - kubectl get pods
        - kubectl get svc
        - echo done
    only: 
        - master

switch-to-blue:
    image: google/cloud-sdk
    stage: switch
    when: manual
    environment:
        name: production
        kubernetes:
          namespace: production
    script:
        - kubectl apply -f app-service-blue.yaml
        - kubectl get pods
        - kubectl get svc
        - echo done
    only: 
        - master

switch-to-green:
    image: google/cloud-sdk
    stage: switch
    when: manual
    environment:
        name: production
        kubernetes:
          namespace: production
    script:
        - echo $KUBE_NAMESPACE
        - echo http://development-$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN
        - kubectl apply -f app-service-blue.yaml
        - kubectl get pods
        - kubectl get svc
        - echo done
    only: 
        - master
