variables:
  USERNAME: senali20119025
  PASSWORD: maneesha123

stages:
  - build
  - deploy
  - switch

docker-build:
    image: docker:latest
    stage: build
    when: manual
    services:
    - docker:dind  
    before_script:
    - docker login -u $USERNAME -p $PASSWORD     
    script:
    - docker build -t "senali20119025/coinbased-exchange-repo:v1" .
    - docker push "senali20119025/coinbased-exchange-repo:v1"

deploy:
    image: google/cloud-sdk
    stage: deploy
    when: manual
    environment:
        name: development
    before_script: 
        - gcloud container clusters get-credentials coinbased-exchange-cluster --zone us-east1-b --project proud-quasar-337917
    script:
        - kubectl apply -f coinbase-deployment.yaml
        - kubectl apply -f coinbase-service.yaml
        - kubectl get pods
        - kubectl get svc
        - echo done
    only: 
        - master