stages:
  - build
  - deploy
  - switch

docker-build:
    image: docker:latest
    stage: build
    when: manual
    services:
    - docker:dind       
    script:
    - docker build -t "us-east1-docker.pkg.dev/proud-quasar-337917/coinbased-docker-repo/coinbased-image" .
    - docker push "us-east1-docker.pkg.dev/proud-quasar-337917/coinbased-docker-repo/coinbased-image:latest"

deploy:
    image: google/cloud-sdk
    stage: deploy
    when: manual
    environment:
        name: development
    before_script: 
        - gcloud container clusters get-credentials coinbased-exchange-cluster
    script:
        - kubectl apply -f coinbase-deployment.yaml
        - kubectl apply -f coinbase-service.yaml
        - kubectl get pods
        - kubectl get svc
        - echo done
    only: 
        - master



